### ISSUE TITLE
Classes not imported

### ISSUE THREAD

**Issue by ThirstyGeo** [njali2001/popsom#1]
Hello, I'm quite interested to use your port of popsom, but there seems to be an issue after install, with the classes.

**For example:**

```
     import popsom as som
     m = som.map(xdim=15, ydim=10, algorithm="som", train=2000)
```

**Gives the error:**

```
AttributeError                            Traceback (most recent call last)
<ipython-input-49-f7f5f62ff140> in <module>()
      1 import popsom as som
----> 2 m = som.map(xdim=15, ydim=10, algorithm="som", train=2000)

AttributeError: module 'popsom' has no attribute 'map'
```

**And checking dir(som) only shows:**

```
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'name']
```

**Comment by njali2001** [comment]
Hi Thirsty,

Thanks for your comments, this package hasn't been wrapped properly. I'm still working on it. Sorry for the inconvenience, I will keep you updated as soon as it ready for install.   

Li

**Comment by lutzhamel** [comment]
Hi Li:
You should really work on your library and make it work.  Also, you should provide some documentation if you haven't done so yet. 
Best,Lutz

    On Sunday, October 7, 2018, 8:26:43 PM EDT, Li Yuan <notifications@github.com> wrote:  
 
 
Hi Thirsty,

Thanks for your comments, this package hasn't been wrapped properly. I'm still working on it. Sorry for the inconvenience, I will keep you updated as soon as it ready for install.

Li

**Comment by njali2001** [comment]
Sure, will do

**Comment by ThirstyGeo** [comment]
I'm quite excited to use it! I have seen you conversations over at the scikit pages; I think that they are incorrect about SOM being an outdated approach (let's not forget how long it took for other machine learning approaches to catch on!)

The good point was made by a few others: SOMs are very common in the natural sciences. My experience is that they deal well with the type of skewed population distributions we routinely encounter.

I know a few other python users (PhD students) also looking forward to your implementation appearing in conda. Just to pass along some positive support!

**Comment by njali2001** [comment]
I am so glad to have your comments and support. You're definitely the one who really understand SOM. I made some updates today (re-package it) and asked some of my friends to verify. I will also prepare the document as Dr.Hamel advised. 

Please feel free to reach me via email if you have further questions or suggestions.

**Comment by ThirstyGeo** [comment]
We're excited to give it a go!

I've just received word of a group coming to the University next week, and hopefully we will be able to sit down with your library. These are people who have been hoping to see better SOM implementation for python (working in the Geology sector).

**Comment by njali2001** [comment]
I will be available next week and very happy to demonstrate our work to your group. 

As you know, SOM can be applied to any kind of research fields. My work was focus on the implementation and evaluation the quality of the model we created. Here is my thesis for your reference if you would like to know more about my previous work  https://digitalcommons.uri.edu/theses/1244/  . And if you want to send me over some data for discussion and analysis, here is my email:  li_yuan@my.uri.edu 

Making SOM impactable is always one of my goal.

**Comment by lutzhamel** [comment]
Hello All:
I figure I chime in.  A couple of important features that make this SOM library different from many others:1) built-in quality measures let's you evaluate the quality of your map in a straightforward manner2) a vectorized version of the training algorithm - currently the fasted single threaded training algorithm for SOM -- single threaded means no special hardware or libraries.  Our experiments have shown that the vectorized version runs 50x faster than the standard implementation and up to 3 times faster than the batchSOM algorithm3) enhanced cluster visualization via starbursts
If you are working on Windows then the vectorized version should be available to use, Li can tell you more about that.  Li is currently still working on porting this to Unix/Linux.
This is a great opportunity to work with an actual user to make this as robust and user friendly as possible.
Thanks,Lutz Hamellutzhamel@uri.edu    On Wednesday, October 10, 2018, 9:43:20 AM EDT, Li Yuan <notifications@github.com> wrote:  
 
 
I will be available next week and very happy to demonstrate our work to your group.

As you know, SOM can be applied to any kind of research fields. My work was focus on the implementation and evaluation the quality of the model we created. Here is my thesis for your reference if you would like to know more about my previous work https://digitalcommons.uri.edu/theses/1244/ . And if you want to send me over some data for discussion and analysis, here is my email: li_yuan@my.uri.edu

Making SOM impactable is always one of my goal.

**Comment by ThirstyGeo** [comment]
Many thanks, Li. I have actually had your thesis open on my desk all week!

**Comment by njali2001** [comment]
Hi Thirsty Geo,

I made tiny adjustment of the program itself, now it should be compatible to different OS. I also put two samples in ReadMe file for your reference. Please feel free to try it and let me know if you have further questions.

**Comment by ThirstyGeo** [comment]
Issue resolved! Many thanks
