### ISSUE TITLE
ValueError in starburst

### ISSUE THREAD

**Issue by VaheC** [njali2001/popsom#3]
While running m.starburst() I got the following error:

ValueError: Input array must be 1 dimensional.

What is the problem ?

Thanks.

**Comment by njali2001** [comment]
Hi, this is a pandas compatibility problem, you can downgrade your pandas's version to 0.20.3. By the way, I am working on this issue right now. You can wait for a while if you are not in hurry.

**Comment by VaheC** [comment]
Hi, please, just let me know when you finish. Thanks.

**Comment by njali2001** [comment]
Sure.

Sincerely,

Li Yuan
________________________________

**Comment by vatsalag99** [comment]
Hi, was this problem solved?

**Comment by njali2001** [comment]
Upgrading pandas brought me more issues, still working on it.

Sincerely,

Li Yuan

________________________________

**Comment by calvintay** [comment]
I have the same issue and would prefer not to downgrade as it seems a lot of my other packages require pandas to be >=0.24.2

Do you know if this will work with pandas 0.24.2?

**Comment by njali2001** [comment]
I'm afraid my code doesn't compatible with pandas >0.24.2. I'm going to fix it this August. Hopefully, it will works eventually.  🤞

**Comment by marcosjacinto** [comment]
Hello there!

I just found out about this som implementation. Congratulations, by the way.

I have the same problem. Hope you can fix it soon.

**Comment by njali2001** [comment]
Hi Marcos,

Fixing the problem is already in my calendar.🤞

**Comment by njali2001** [comment]
@vatsalag99 @VaheC @marcosjacinto @calvintay  The issue has been fixed, please feel free to try it again and let me know it is works for you. Thanks!

**Comment by marcosjacinto** [comment]
Thanks! I'll test it out!
